package pkg

import (
	"k8s.io/gengo/args"
	"k8s.io/gengo/generator"
)

func Packages(context *generator.Context, arguments *args.GeneratorArgs) generator.Packages {
	return generator.Packages{
		&generator.DefaultPackage{
			PackageName: "result",
			PackagePath: arguments.OutputPackagePath,
			PackageDocumentation: []byte(
				`// Package result is generated by lab2`),
			GeneratorFunc: func(context *generator.Context) []generator.Generator {
				return []generator.Generator{
					&LabGenerator{
						DefaultGen: generator.DefaultGen{
							OptionalName: "lab2_generated",
						},
						outputPkg:     arguments.OutputPackagePath,
						importTracker: generator.NewImportTracker(),
					},
				}
			},
		},
	}
}
